- name: Play level variables
  hosts: localhost
  connection: local
  vars:
    Course: "DevOps with AWS"
    Duration: "140 Hours"
    Trainer: "Sandeep Narayana"
  tasks:
  - name: Print Course Name
    vars:
      Course: "DevOps with Azure"
    ansible.builtin.debug:
      msg: "Course Name is {{ Course }}, Trainer is {{Trainer }}"