- name: play level variables
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    duration: "140HRS"
    trainer: "siva"
  tasks:
  - name: print variables
    vars:
      course: Ansible    
    ansible.builtin.debug:
      msg: "Course is: {{ course }}, Trainer is: {{ trainer }}"