- name: print username and password
  hosts: local
  connection: local
  var_files:
  - name: username
    prompt: Please enter your password
    private: false

  - name: password
    prompt: Please enter your password
    private: true

  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "Username is: {{ username }}, password is: {{ password }}"