- name: Play level variables
  hosts: Local
  connection: local
  vars_files:
  - 06-course.yaml
  tasks:
  - name: Print Course Name
    ansible.builtin.debug:
      msg: "Course Name is {{ Course }}, Trainer is {{Trainer }}"