- name: Play level variables
  hosts: localhost
  connection: local
  vars_files:
  - 06-course.yaml
  tasks:
  - name: Print Course Name
    vars:
      Course: "DevOps with Azure"
    ansible.builtin.debug:
      msg: "Course Name is {{ Course }}, Trainer is {{Trainer }}"