- name: check the number lesshan 10 or not
  hosts: local
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7
  tasks:
  - name: is ansible is greathan 7
    ansible.builtin.debug:
      msg: "yes, more than 5 sessions"
    when: NUMBER_OF_SESSIONS > 5