- name: isntall packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: #list of map
    - { name: "mysql", state: "absent"}
    - { name: "nginx", state: "present"}
    - { name: "tree", state: "present"}